### ISSUE TITLE
DA Scraper just downloads a hot mess of garbage

### ISSUE THREAD

**Issue by ghost** [herp-a-derp/xA-Scraper#1]
Tons of extensionless files of garbled characters.

**Comment by Aidolii** [comment]
Just as a supplemental, the only scraper I know of that seems to scrape DA without problems is this one: https://github.com/Aidolii/dagr/blob/patch-4/dagr/dagr.py

Requires a login with the new 'eclipse' theme disabled on it (seems to be an account setting rather than a cookie setting, strangely enough).

**Comment by herp-a-derp** [comment]
That was weird. Somehow I wasn't watching my own damn projects.

It looks like the files are correct, just incorrectly named (they open fine with a image viewer smart enough to ignore the extension).

**Comment by Aidolii** [comment]
I mean, the filenames are pretty important. Could this be resolved? I use one of only a handful of image viewers that support GPU acceleration (helps you scroll through large pictures very fast) and it wants extensions. Plus, I have no way of determining what's what. The localhost image viewer has never worked right for me.

**Comment by Aidolii** [comment]
Oops. I hit Close and comment instead of Comment by accident.

**Comment by herp-a-derp** [comment]
Ok, file extensions should be autoderived via libmagic now.
